<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\Api\AdvertisementController;
use App\Http\Controllers\Api\ImagingController;
use App\Http\Controllers\Api\TicketController;
use App\Http\Controllers\Api\VerifyController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DiscussionActionController;
use App\Http\Controllers\ExtraHabbletController;
use App\Http\Controllers\FriendManagementController;
use App\Http\Controllers\GroupActionController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\HabbletController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\HomeInventoryController;
use App\Http\Controllers\HomeStoreController;
use App\Http\Controllers\HomeWidgetController;
use App\Http\Controllers\HousekeepingBadgesController;
use App\Http\Controllers\HousekeepingCatalogueController;
use App\Http\Controllers\HousekeepingController;
use App\Http\Controllers\HousekeepingGameDataController;
use App\Http\Controllers\HousekeepingGroupsController;
use App\Http\Controllers\HousekeepingInfobusController;
use App\Http\Controllers\HousekeepingRoomAssetsController;
use App\Http\Controllers\HousekeepingRoomsController;
use App\Http\Controllers\HousekeepingSiteController;
use App\Http\Controllers\HousekeepingTransactionsController;
use App\Http\Controllers\HousekeepingUsersController;
use App\Http\Controllers\InviteController;
use App\Http\Controllers\MinimailController;
use App\Http\Controllers\NoteEditorController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicSiteController;
use App\Http\Controllers\QuickmenuController;
use App\Http\Controllers\RecoveryController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\TraxController;
use App\Services\HavanaConfig;
use App\Services\HotelStatus;
use App\Services\LegacyTemplate;
use Illuminate\Support\Facades\Route;

Route::get('/_havana/status', function (HavanaConfig $config, HotelStatus $hotelStatus) {
    $status = $hotelStatus->snapshot();

    return response()->json([
        'app' => 'HavanaPHP',
        'siteName' => $config->string('site.name'),
        'templatePath' => config('havana.template_path').'/'.config('havana.template_name'),
        'publicPath' => config('havana.public_path'),
        'housekeepingPath' => config('havana.housekeeping_path'),
        'serverOnline' => $status['serverOnline'],
        'usersOnline' => $status['usersOnline'],
    ]);
});

$housekeepingPath = '/'.trim((string) config('havana.housekeeping_path', 'allseeingeye/hk'), '/');
Route::get($housekeepingPath, [HousekeepingController::class, 'dashboard']);
Route::get($housekeepingPath.'/', [HousekeepingController::class, 'dashboard']);
Route::match(['get', 'post'], $housekeepingPath.'/login', [HousekeepingController::class, 'login']);
Route::get($housekeepingPath.'/api/ban', [HousekeepingUsersController::class, 'ban']);
Route::get($housekeepingPath.'/logout', [HousekeepingController::class, 'logout']);
Route::match(['get', 'post'], $housekeepingPath.'/transaction/lookup', [HousekeepingTransactionsController::class, 'lookup']);
Route::get($housekeepingPath.'/transaction/track_item', [HousekeepingTransactionsController::class, 'trackItem']);
Route::match(['get', 'post'], $housekeepingPath.'/articles', [HousekeepingSiteController::class, 'articles']);
Route::match(['get', 'post'], $housekeepingPath.'/articles/create', [HousekeepingSiteController::class, 'createArticle']);
Route::match(['get', 'post'], $housekeepingPath.'/articles/edit', [HousekeepingSiteController::class, 'editArticle']);
Route::get($housekeepingPath.'/articles/delete', [HousekeepingSiteController::class, 'deleteArticle']);
Route::match(['get', 'post'], $housekeepingPath.'/configurations', [HousekeepingSiteController::class, 'configurations']);
Route::match(['get', 'post'], $housekeepingPath.'/catalogue/edit_frontpage', [HousekeepingCatalogueController::class, 'frontpage']);
Route::get($housekeepingPath.'/catalogue/pages', [HousekeepingCatalogueController::class, 'pages']);
Route::match(['get', 'post'], $housekeepingPath.'/catalogue/pages/edit', [HousekeepingCatalogueController::class, 'editPage']);
Route::get($housekeepingPath.'/catalogue/pages/delete', [HousekeepingCatalogueController::class, 'deletePage']);
Route::get($housekeepingPath.'/catalogue/items', [HousekeepingCatalogueController::class, 'items']);
Route::match(['get', 'post'], $housekeepingPath.'/catalogue/items/edit', [HousekeepingCatalogueController::class, 'editItem']);
Route::get($housekeepingPath.'/catalogue/items/delete', [HousekeepingCatalogueController::class, 'deleteItem']);
Route::get($housekeepingPath.'/catalogue/packages', [HousekeepingCatalogueController::class, 'packages']);
Route::match(['get', 'post'], $housekeepingPath.'/catalogue/packages/edit', [HousekeepingCatalogueController::class, 'editPackage']);
Route::get($housekeepingPath.'/catalogue/packages/delete', [HousekeepingCatalogueController::class, 'deletePackage']);
Route::match(['get', 'post'], $housekeepingPath.'/catalogue/sale_badges', [HousekeepingCatalogueController::class, 'saleBadges']);
Route::get($housekeepingPath.'/catalogue/sale_badges/delete', [HousekeepingCatalogueController::class, 'deleteSaleBadge']);
Route::get($housekeepingPath.'/catalogue/collectables', [HousekeepingCatalogueController::class, 'collectables']);
Route::match(['get', 'post'], $housekeepingPath.'/catalogue/collectables/edit', [HousekeepingCatalogueController::class, 'editCollectable']);
Route::get($housekeepingPath.'/catalogue/collectables/delete', [HousekeepingCatalogueController::class, 'deleteCollectable']);
Route::get($housekeepingPath.'/item_definitions', [HousekeepingGameDataController::class, 'itemDefinitions']);
Route::match(['get', 'post'], $housekeepingPath.'/item_definitions/edit', [HousekeepingGameDataController::class, 'editItemDefinition']);
Route::get($housekeepingPath.'/item_definitions/delete', [HousekeepingGameDataController::class, 'deleteItemDefinition']);
Route::get($housekeepingPath.'/vouchers', [HousekeepingGameDataController::class, 'vouchers']);
Route::match(['get', 'post'], $housekeepingPath.'/vouchers/edit', [HousekeepingGameDataController::class, 'editVoucher']);
Route::get($housekeepingPath.'/vouchers/delete', [HousekeepingGameDataController::class, 'deleteVoucher']);
Route::get($housekeepingPath.'/wordfilter', [HousekeepingGameDataController::class, 'wordfilter']);
Route::match(['get', 'post'], $housekeepingPath.'/wordfilter/edit', [HousekeepingGameDataController::class, 'editWordfilter']);
Route::get($housekeepingPath.'/wordfilter/delete', [HousekeepingGameDataController::class, 'deleteWordfilter']);
Route::get($housekeepingPath.'/recycler_rewards', [HousekeepingGameDataController::class, 'recyclerRewards']);
Route::match(['get', 'post'], $housekeepingPath.'/recycler_rewards/edit', [HousekeepingGameDataController::class, 'editRecyclerReward']);
Route::get($housekeepingPath.'/recycler_rewards/delete', [HousekeepingGameDataController::class, 'deleteRecyclerReward']);
Route::get($housekeepingPath.'/room_categories', [HousekeepingGameDataController::class, 'roomCategories']);
Route::match(['get', 'post'], $housekeepingPath.'/room_categories/edit', [HousekeepingGameDataController::class, 'editRoomCategory']);
Route::get($housekeepingPath.'/room_categories/delete', [HousekeepingGameDataController::class, 'deleteRoomCategory']);
Route::get($housekeepingPath.'/room_models', [HousekeepingGameDataController::class, 'roomModels']);
Route::match(['get', 'post'], $housekeepingPath.'/room_models/edit', [HousekeepingGameDataController::class, 'editRoomModel']);
Route::get($housekeepingPath.'/room_models/delete', [HousekeepingGameDataController::class, 'deleteRoomModel']);
Route::match(['get', 'post'], $housekeepingPath.'/room_ads', [HousekeepingRoomAssetsController::class, 'roomAds']);
Route::match(['get', 'post'], $housekeepingPath.'/room_ads/create', [HousekeepingRoomAssetsController::class, 'createRoomAd']);
Route::get($housekeepingPath.'/room_ads/delete', [HousekeepingRoomAssetsController::class, 'deleteRoomAd']);
Route::match(['get', 'post'], $housekeepingPath.'/room_badges', [HousekeepingRoomAssetsController::class, 'roomBadges']);
Route::match(['get', 'post'], $housekeepingPath.'/room_badges/create', [HousekeepingRoomAssetsController::class, 'createRoomBadge']);
Route::get($housekeepingPath.'/room_badges/delete', [HousekeepingRoomAssetsController::class, 'deleteRoomBadge']);
Route::get($housekeepingPath.'/rooms', [HousekeepingRoomsController::class, 'rooms']);
Route::match(['get', 'post'], $housekeepingPath.'/rooms/edit', [HousekeepingRoomsController::class, 'edit']);
Route::get($housekeepingPath.'/rooms/hide', [HousekeepingRoomsController::class, 'hide']);
Route::get($housekeepingPath.'/rooms/staff_pick', [HousekeepingRoomsController::class, 'staffPick']);
Route::get($housekeepingPath.'/rooms/delete', [HousekeepingRoomsController::class, 'delete']);
Route::get($housekeepingPath.'/groups', [HousekeepingGroupsController::class, 'groups']);
Route::match(['get', 'post'], $housekeepingPath.'/groups/edit', [HousekeepingGroupsController::class, 'edit']);
Route::match(['get', 'post'], $housekeepingPath.'/groups/member', [HousekeepingGroupsController::class, 'member']);
Route::match(['get', 'post'], $housekeepingPath.'/groups/thread', [HousekeepingGroupsController::class, 'thread']);
Route::get($housekeepingPath.'/groups/reply', [HousekeepingGroupsController::class, 'reply']);
Route::get($housekeepingPath.'/groups/staff_pick', [HousekeepingGroupsController::class, 'staffPick']);
Route::get($housekeepingPath.'/groups/delete', [HousekeepingGroupsController::class, 'delete']);
Route::get($housekeepingPath.'/badges', [HousekeepingBadgesController::class, 'badges']);
Route::match(['get', 'post'], $housekeepingPath.'/badges/grant', [HousekeepingBadgesController::class, 'grant']);
Route::match(['get', 'post'], $housekeepingPath.'/badges/update', [HousekeepingBadgesController::class, 'update']);
Route::get($housekeepingPath.'/badges/remove', [HousekeepingBadgesController::class, 'remove']);
Route::match(['get', 'post'], $housekeepingPath.'/users/search', [HousekeepingUsersController::class, 'search']);
Route::match(['get', 'post'], $housekeepingPath.'/users/create', [HousekeepingUsersController::class, 'create']);
Route::match(['get', 'post'], $housekeepingPath.'/users/edit', [HousekeepingUsersController::class, 'edit']);
Route::get($housekeepingPath.'/users/imitate/{username}', [HousekeepingUsersController::class, 'imitate']);
Route::get($housekeepingPath.'/bans', [HousekeepingUsersController::class, 'bans']);
Route::get($housekeepingPath.'/infobus_polls', [HousekeepingInfobusController::class, 'polls']);
Route::match(['get', 'post'], $housekeepingPath.'/infobus_polls/create', [HousekeepingInfobusController::class, 'create']);
Route::match(['get', 'post'], $housekeepingPath.'/infobus_polls/edit', [HousekeepingInfobusController::class, 'edit']);
Route::get($housekeepingPath.'/infobus_polls/delete', [HousekeepingInfobusController::class, 'delete']);
Route::get($housekeepingPath.'/infobus_polls/view_results', [HousekeepingInfobusController::class, 'viewResults']);
Route::get($housekeepingPath.'/infobus_polls/clear_results', [HousekeepingInfobusController::class, 'clearResults']);
Route::get($housekeepingPath.'/infobus_polls/send_poll', [HousekeepingInfobusController::class, 'sendPoll']);
Route::get($housekeepingPath.'/infobus_polls/close_event', [HousekeepingInfobusController::class, 'closeEvent']);
Route::get($housekeepingPath.'/infobus_polls/door_status', [HousekeepingInfobusController::class, 'doorStatus']);
Route::match(['get', 'post'], '/habblet/ajax/preview_news_article', [HousekeepingSiteController::class, 'previewNewsArticle']);

Route::get('/', function (LegacyTemplate $template) {
    return response($template->render('index_v32'));
});

Route::get('/index', fn (LegacyTemplate $template) => response($template->render('index_v32')));
Route::get('/home', fn (LegacyTemplate $template) => response($template->render('index_v32')));
Route::get('/maintenance', [PublicSiteController::class, 'maintenance']);
Route::get('/home/{user}/id', [HomeController::class, 'show']);
Route::get('/home/{user}', [HomeController::class, 'show']);
Route::get('/community', [PublicSiteController::class, 'community']);
Route::get('/articles', [PublicSiteController::class, 'articles']);
Route::get('/articles/archive', [PublicSiteController::class, 'articles']);
Route::get('/articles/category/{category}', [PublicSiteController::class, 'articles']);
Route::get('/articles/{article}', [PublicSiteController::class, 'articles']);
Route::get('/community/events', [PublicSiteController::class, 'events']);
Route::get('/community/events/archive', [PublicSiteController::class, 'events']);
Route::get('/community/events/category/{category}', [PublicSiteController::class, 'events']);
Route::get('/community/events/{article}', [PublicSiteController::class, 'events']);
Route::get('/community/fansites', [PublicSiteController::class, 'fansites']);
Route::get('/community/fansites/archive', [PublicSiteController::class, 'fansites']);
Route::get('/community/fansites/category/{category}', [PublicSiteController::class, 'fansites']);
Route::get('/community/fansites/{article}', [PublicSiteController::class, 'fansites']);
Route::get('/games', [PublicSiteController::class, 'games']);
Route::get('/games/score_all_time', [PublicSiteController::class, 'gamesAllTime']);
Route::match(['get', 'post'], '/habblet/personalhighscores', [PublicSiteController::class, 'personalHighscores']);
Route::get('/credits', [PublicSiteController::class, 'credits']);
Route::get('/credits/history', [PublicSiteController::class, 'creditsHistory']);
Route::get('/credits/pixels', [PublicSiteController::class, 'pixels']);
Route::get('/credits/club', [PublicSiteController::class, 'club']);
Route::get('/credits/club/tryout', [PublicSiteController::class, 'clubTryout']);
Route::get('/credits/collectables', [PublicSiteController::class, 'collectables']);
Route::get('/help/{path?}', [PublicSiteController::class, 'help'])->where('path', '.*');
Route::match(['get', 'post'], '/grouppurchase/group_create_form', [GroupActionController::class, 'groupCreateForm']);
Route::match(['get', 'post'], '/grouppurchase/purchase_confirmation', [GroupActionController::class, 'purchaseConfirmation']);
Route::match(['get', 'post'], '/grouppurchase/purchase_ajax', [GroupActionController::class, 'purchaseAjax']);
Route::get('/groups/actions/startEditingSession/{group}', [GroupActionController::class, 'startEditingSession']);
Route::match(['get', 'post'], '/groups/actions/cancelEditingSession', [GroupActionController::class, 'cancelEditingSession']);
Route::match(['get', 'post'], '/groups/actions/group_settings', [GroupActionController::class, 'groupSettings']);
Route::match(['get', 'post'], '/groups/actions/saveEditingSession', [GroupActionController::class, 'saveEditingSession']);
Route::match(['get', 'post'], '/groups/actions/update_group_settings', [GroupActionController::class, 'updateGroupSettings']);
Route::match(['get', 'post'], '/groups/actions/check_group_url', [GroupActionController::class, 'checkGroupUrl']);
Route::match(['get', 'post'], '/groups/actions/show_badge_editor', [GroupActionController::class, 'showBadgeEditor']);
Route::match(['get', 'post'], '/groups/actions/update_group_badge', [GroupActionController::class, 'updateGroupBadge']);
Route::match(['get', 'post'], '/groups/actions/confirm_delete_group', [GroupActionController::class, 'confirmDeleteGroup']);
Route::match(['get', 'post'], '/groups/actions/delete_group', [GroupActionController::class, 'deleteGroup']);
Route::match(['get', 'post'], '/groups/actions/join', [GroupActionController::class, 'join']);
Route::match(['get', 'post'], '/groups/actions/confirm_leave', [GroupActionController::class, 'confirmLeave']);
Route::match(['get', 'post'], '/groups/actions/leave', [GroupActionController::class, 'leave']);
Route::match(['get', 'post'], '/groups/actions/confirm_select_favorite', [GroupActionController::class, 'confirmSelectFavourite']);
Route::match(['get', 'post'], '/groups/actions/select_favorite', [GroupActionController::class, 'selectFavourite']);
Route::match(['get', 'post'], '/groups/actions/confirm_deselect_favorite', [GroupActionController::class, 'confirmDeselectFavourite']);
Route::match(['get', 'post'], '/groups/actions/deselect_favorite', [GroupActionController::class, 'deselectFavourite']);
Route::match(['get', 'post'], '/myhabbo/tag/addgrouptag', [GroupActionController::class, 'addGroupTag']);
Route::match(['get', 'post'], '/myhabbo/tag/listgrouptags', [GroupActionController::class, 'listGroupTags']);
Route::match(['get', 'post'], '/myhabbo/tag/removegrouptag', [GroupActionController::class, 'removeGroupTag']);
Route::match(['get', 'post'], '/myhabbo/groups/memberlist', [GroupActionController::class, 'memberList']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/confirm_revoke_rights', [GroupActionController::class, 'confirmRevokeRights']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/revoke_rights', [GroupActionController::class, 'revokeRights']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/confirm_give_rights', [GroupActionController::class, 'confirmGiveRights']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/give_rights', [GroupActionController::class, 'giveRights']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/confirm_remove', [GroupActionController::class, 'confirmRemove']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/remove', [GroupActionController::class, 'remove']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/confirm_accept', [GroupActionController::class, 'confirmAccept']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/accept', [GroupActionController::class, 'accept']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/confirm_decline', [GroupActionController::class, 'confirmDecline']);
Route::match(['get', 'post'], '/myhabbo/groups/batch/decline', [GroupActionController::class, 'decline']);
Route::get('/groups/{group}/id/discussions/{thread}/id/page/{page}', [GroupController::class, 'discussion'])->whereNumber('thread')->whereNumber('page');
Route::get('/groups/{group}/discussions/{thread}/id/page/{page}', [GroupController::class, 'discussion'])->whereNumber('thread')->whereNumber('page');
Route::get('/groups/{group}/id/discussions/{thread}/id', [GroupController::class, 'discussion'])->whereNumber('thread');
Route::get('/groups/{group}/discussions/{thread}/id', [GroupController::class, 'discussion'])->whereNumber('thread');
Route::get('/groups/{group}/id/discussions/page/{page}', [GroupController::class, 'discussions'])->whereNumber('page');
Route::get('/groups/{group}/discussions/page/{page}', [GroupController::class, 'discussions'])->whereNumber('page');
Route::get('/groups/{group}/id/discussions', [GroupController::class, 'discussions']);
Route::get('/groups/{group}/discussions', [GroupController::class, 'discussions']);
Route::match(['get', 'post'], '/discussions/actions/pingsession', [DiscussionActionController::class, 'pingSession']);
Route::match(['get', 'post'], '/discussions/actions/newtopic', [DiscussionActionController::class, 'newTopic']);
Route::match(['get', 'post'], '/discussions/actions/savetopic', [DiscussionActionController::class, 'saveTopic']);
Route::match(['get', 'post'], '/discussions/actions/previewtopic', [DiscussionActionController::class, 'previewTopic']);
Route::match(['get', 'post'], '/discussions/actions/previewpost', [DiscussionActionController::class, 'previewPost']);
Route::match(['get', 'post'], '/discussions/actions/opentopicsettings', [DiscussionActionController::class, 'openTopicSettings']);
Route::match(['get', 'post'], '/discussions/actions/confirm_delete_topic', [DiscussionActionController::class, 'confirmDeleteTopic']);
Route::match(['get', 'post'], '/discussions/actions/deletetopic', [DiscussionActionController::class, 'deleteTopic']);
Route::match(['get', 'post'], '/discussions/actions/savetopicsettings', [DiscussionActionController::class, 'saveTopicSettings']);
Route::match(['get', 'post'], '/discussions/actions/updatepost', [DiscussionActionController::class, 'updatePost']);
Route::match(['get', 'post'], '/discussions/actions/deletepost', [DiscussionActionController::class, 'deletePost']);
Route::match(['get', 'post'], '/discussions/actions/savepost', [DiscussionActionController::class, 'savePost']);
Route::get('/groups/{group}/id', [GroupController::class, 'show']);
Route::get('/groups/{group}', [GroupController::class, 'show']);
Route::get('/tag', [TagController::class, 'index']);
Route::get('/tag/search', [TagController::class, 'search']);
Route::get('/tag/{tag}', [TagController::class, 'search']);

Route::get('/me', [AccountController::class, 'me']);
Route::get('/welcome', [AccountController::class, 'welcome']);
Route::get('/login_popup', [AccountController::class, 'loginPopup']);
Route::get('/account/login', [AccountController::class, 'loginPopup']);
Route::match(['get', 'post'], '/account/reauthenticate', [AccountController::class, 'reauthenticate']);
Route::match(['get', 'post'], '/account/submit', [AccountController::class, 'submit']);
Route::match(['get', 'post'], '/account/logout', [AccountController::class, 'logout']);
Route::get('/account/banned', [AccountController::class, 'banned']);
Route::get('/security_check', [AccountController::class, 'securityCheck']);
Route::match(['get', 'post'], '/account/password/forgot', [RecoveryController::class, 'forgot']);
Route::match(['get', 'post'], '/account/password/recovery', [RecoveryController::class, 'recovery']);
Route::get('/account/activate', [RecoveryController::class, 'activate']);

Route::match(['get', 'post'], '/register', [RegisterController::class, 'register']);
Route::get('/register/cancel', [RegisterController::class, 'cancel']);
Route::get('/captcha.jpg', [RegisterController::class, 'captcha']);

Route::get('/components/updateHabboCount', [ClientController::class, 'updateHabboCount']);
Route::get('/client', [ClientController::class, 'client']);
Route::match(['get', 'post'], '/clientlog/update', [ClientController::class, 'blank']);
Route::match(['get', 'post'], '/clientlog/nojs', [ClientController::class, 'blank']);
Route::get('/cacheCheck', [ClientController::class, 'blank']);
Route::get('/shockwave_client', [ClientController::class, 'shockwave']);
Route::get('/flash_client', [ClientController::class, 'flash']);
Route::get('/client_popup/install_shockwave', [ClientController::class, 'installShockwave']);
Route::get('/client_error', [ClientController::class, 'clientError']);
Route::get('/client_connection_failed', [ClientController::class, 'clientConnectionFailed']);

Route::match(['get', 'post'], '/habblet/ajax/namecheck', [HabbletController::class, 'nameCheck']);
Route::match(['get', 'post'], '/habblet/ajax/updatemotto', [HabbletController::class, 'updateMotto']);
Route::match(['get', 'post'], '/habblet/ajax/roomselectionCreate', [HabbletController::class, 'roomSelectionCreate']);
Route::match(['get', 'post'], '/habblet/ajax/roomselectionConfirm', [HabbletController::class, 'roomSelectionConfirm']);
Route::match(['get', 'post'], '/habblet/ajax/roomselectionHide', [HabbletController::class, 'roomSelectionHide']);
Route::get('/components/roomNavigation', [HabbletController::class, 'roomNavigation']);
Route::get('/habblet/ajax/nextgift', [HabbletController::class, 'nextGift']);
Route::match(['get', 'post'], '/habblet/ajax/giftqueueHide', [HabbletController::class, 'giftQueueHide']);
Route::match(['get', 'post'], '/myhabbo/tag/add', [HabbletController::class, 'addTag']);
Route::match(['get', 'post'], '/myhabbo/tag/remove', [HabbletController::class, 'removeTag']);
Route::match(['get', 'post'], '/remove_all_tags', [HabbletController::class, 'removeAllTags']);
Route::get('/habblet/mytagslist', [HabbletController::class, 'myTagsList']);
Route::match(['get', 'post'], '/habblet/ajax/tagfight', [HabbletController::class, 'tagFight']);
Route::match(['get', 'post'], '/habblet/ajax/tagmatch', [HabbletController::class, 'tagMatch']);
Route::match(['get', 'post'], '/habblet/ajax/tagsearch', [TagController::class, 'ajaxSearch']);
Route::match(['get', 'post'], '/habblet/ajax/redeemvoucher', [HabbletController::class, 'redeemVoucher']);
Route::get('/habblet/proxy', [HabbletController::class, 'proxy']);
Route::get('/habblet/cproxy', [HabbletController::class, 'clientProxy']);
Route::match(['get', 'post'], '/habblet/ajax/clear_hand', [HabbletController::class, 'clearHand']);
Route::match(['get', 'post'], '/habblet/ajax/token_generate', [HabbletController::class, 'tokenGenerate']);
Route::match(['get', 'post'], '/habblet/ajax/removeFeedItem', [ExtraHabbletController::class, 'removeFeedItem']);
Route::match(['get', 'post'], '/habblet/ajax/load_events', [ExtraHabbletController::class, 'loadEvents']);
Route::match(['get', 'post'], '/habblet/ajax/collectiblesConfirm', [ExtraHabbletController::class, 'collectiblesConfirm']);
Route::match(['get', 'post'], '/habblet/ajax/collectiblesPurchase', [ExtraHabbletController::class, 'collectiblesPurchase']);
Route::match(['get', 'post'], '/habboclub/habboclub_confirm', [ExtraHabbletController::class, 'habboClubConfirm']);
Route::match(['get', 'post'], '/habboclub/habboclub_subscribe', [ExtraHabbletController::class, 'habboClubSubscribe']);
Route::match(['get', 'post'], '/habboclub/habboclub_reminder_remove', [ExtraHabbletController::class, 'habboClubReminderRemove']);
Route::get('/habblet/ajax/habboclub_enddate', [ExtraHabbletController::class, 'habboClubEnddate']);
Route::match(['get', 'post'], '/habblet/ajax/habboclub_gift', [ExtraHabbletController::class, 'habboClubGift']);
Route::match(['get', 'post'], '/habblet/ajax/mgmgetinvitelink', [InviteController::class, 'inviteLink']);
Route::match(['get', 'post'], '/habblet/habbosearchcontent', [InviteController::class, 'searchContent']);
Route::match(['get', 'post'], '/habblet/ajax/confirmAddFriend', [InviteController::class, 'confirmAddFriend']);
Route::match(['get', 'post'], '/habblet/ajax/addFriend', [InviteController::class, 'addFriend']);
Route::match(['get', 'post'], '/myhabbo/friends/add', [InviteController::class, 'add']);
Route::get('/myhabbo/startSession/{user}', [HomeController::class, 'startEditingSession']);
Route::get('/myhabbo/cancel/{user}', [HomeController::class, 'cancelEditingSession']);
Route::match(['get', 'post'], '/myhabbo/save', [HomeController::class, 'save']);
Route::match(['get', 'post'], '/myhabbo/tag/list', [HomeController::class, 'tagList']);
Route::match(['get', 'post'], '/myhabbo/noteeditor/editor', [NoteEditorController::class, 'editor']);
Route::match(['get', 'post'], '/myhabbo/noteeditor/preview', [NoteEditorController::class, 'preview']);
Route::get('/myhabbo/linktool/search', [NoteEditorController::class, 'search']);
Route::match(['get', 'post'], '/myhabbo/noteeditor/place', [NoteEditorController::class, 'place']);
Route::match(['get', 'post'], '/myhabbo/stickie/edit', [NoteEditorController::class, 'stickieEdit']);
Route::match(['get', 'post'], '/myhabbo/stickie/delete', [NoteEditorController::class, 'stickieDelete']);
Route::match(['get', 'post'], '/myhabbo/store/inventory', [HomeInventoryController::class, 'inventory']);
Route::match(['get', 'post'], '/myhabbo/store/inventory_items', [HomeInventoryController::class, 'inventoryItems']);
Route::match(['get', 'post'], '/myhabbo/store/inventory_preview', [HomeInventoryController::class, 'inventoryPreview']);
Route::match(['get', 'post'], '/myhabbo/sticker/place_sticker', [HomeInventoryController::class, 'placeSticker']);
Route::match(['get', 'post'], '/myhabbo/sticker/remove_sticker', [HomeInventoryController::class, 'removeSticker']);
Route::match(['get', 'post'], '/myhabbo/widget/add', [HomeInventoryController::class, 'placeWidget']);
Route::match(['get', 'post'], '/myhabbo/widget/delete', [HomeInventoryController::class, 'removeWidget']);
Route::match(['get', 'post'], '/myhabbo/widget/edit', [HomeInventoryController::class, 'editWidget']);
Route::match(['get', 'post'], '/myhabbo/store/main', [HomeStoreController::class, 'main']);
Route::match(['get', 'post'], '/myhabbo/store/items', [HomeStoreController::class, 'items']);
Route::match(['get', 'post'], '/myhabbo/store/preview', [HomeStoreController::class, 'preview']);
Route::match(['get', 'post'], '/myhabbo/store/purchase_confirm', [HomeStoreController::class, 'purchaseConfirm']);
Route::match(['get', 'post'], '/myhabbo/store/background_warning', [HomeStoreController::class, 'backgroundWarning']);
Route::match(['get', 'post'], '/myhabbo/store/purchase_stickers', [HomeStoreController::class, 'purchaseStickers']);
Route::match(['get', 'post'], '/myhabbo/store/purchase_backgrounds', [HomeStoreController::class, 'purchaseBackgrounds']);
Route::match(['get', 'post'], '/myhabbo/store/purchase_stickie_notes', [HomeStoreController::class, 'purchaseStickieNotes']);
Route::match(['get', 'post'], '/myhabbo/traxplayer/select_song', [TraxController::class, 'selectSong']);
Route::get('/myhabbo/rating/rate', [HomeWidgetController::class, 'rate']);
Route::get('/myhabbo/rating/reset_ratings', [HomeWidgetController::class, 'resetRatings']);
Route::match(['get', 'post'], '/myhabbo/groups/groupinfo', [HomeWidgetController::class, 'groupInfo']);
Route::match(['get', 'post'], '/myhabbo/avatarlist/membersearchpaging', [HomeWidgetController::class, 'memberSearchPaging']);
Route::match(['get', 'post'], '/myhabbo/badgelist/badgepaging', [HomeWidgetController::class, 'badgePaging']);
Route::match(['get', 'post'], '/myhabbo/avatarlist/friendsearchpaging', [HomeWidgetController::class, 'friendSearchPaging']);
Route::match(['get', 'post'], '/myhabbo/avatarlist/avatarinfo', [HomeWidgetController::class, 'avatarInfo']);
Route::match(['get', 'post'], '/myhabbo/guestbook/preview', [HomeWidgetController::class, 'guestbookPreview']);
Route::match(['get', 'post'], '/myhabbo/guestbook/add', [HomeWidgetController::class, 'guestbookAdd']);
Route::match(['get', 'post'], '/myhabbo/guestbook/remove', [HomeWidgetController::class, 'guestbookRemove']);
Route::match(['get', 'post'], '/myhabbo/guestbook/configure', [HomeWidgetController::class, 'guestbookConfigure']);

Route::match(['get', 'post'], '/minimail/loadMessages', [MinimailController::class, 'loadMessages']);
Route::get('/minimail/recipients', [MinimailController::class, 'recipients']);
Route::match(['get', 'post'], '/minimail/preview', [MinimailController::class, 'preview']);
Route::match(['get', 'post'], '/minimail/sendMessage', [MinimailController::class, 'sendMessage']);
Route::get('/minimail/loadMessage', [MinimailController::class, 'loadMessage']);
Route::match(['get', 'post'], '/minimail/deleteMessage', [MinimailController::class, 'deleteMessage']);
Route::match(['get', 'post'], '/minimail/undeleteMessage', [MinimailController::class, 'undeleteMessage']);
Route::match(['get', 'post'], '/minimail/emptyTrash', [MinimailController::class, 'emptyTrash']);

Route::get('/quickmenu/groups', [QuickmenuController::class, 'groups']);
Route::get('/quickmenu/rooms', [QuickmenuController::class, 'rooms']);
Route::get('/quickmenu/friends_all', [QuickmenuController::class, 'friends']);

Route::match(['get', 'post'], '/friendmanagement/ajax/editCategory', [FriendManagementController::class, 'editCategory']);
Route::match(['get', 'post'], '/friendmanagement/ajax/createcategory', [FriendManagementController::class, 'createCategory']);
Route::match(['get', 'post'], '/friendmanagement/ajax/deletecategory', [FriendManagementController::class, 'deleteCategory']);
Route::match(['get', 'post'], '/friendmanagement/ajax/viewcategory', [FriendManagementController::class, 'viewCategory']);
Route::get('/friendmanagement/ajax/updatecategoryoptions', [FriendManagementController::class, 'updateCategoryOptions']);
Route::match(['get', 'post'], '/friendmanagement/ajax/movefriends', [FriendManagementController::class, 'moveFriends']);
Route::match(['get', 'post'], '/friendmanagement/ajax/deletefriends', [FriendManagementController::class, 'deleteFriends']);

Route::get('/profile', [ProfileController::class, 'profile']);
Route::get('/profile/verify', [ProfileController::class, 'verify']);
Route::match(['get', 'post'], '/profile/send_email', [ProfileController::class, 'sendEmail']);
Route::match(['get', 'post'], '/profile/wardrobeStore', [ProfileController::class, 'wardrobeStore']);
Route::match(['get', 'post'], '/profile/passwordupdate', [ProfileController::class, 'passwordUpdate']);
Route::match(['get', 'post'], '/profile/emailupdate', [ProfileController::class, 'emailUpdate']);
Route::match(['get', 'post'], '/profile/characterupdate', [ProfileController::class, 'characterUpdate']);
Route::match(['get', 'post'], '/profile/profile.action', [ProfileController::class, 'action']);
Route::match(['get', 'post'], '/profile/profileupdate', [ProfileController::class, 'profileUpdate']);
Route::match(['get', 'post'], '/profile/securitysettingupdate', [ProfileController::class, 'securitySettingUpdate']);
Route::get('/club', [ProfileController::class, 'club']);

Route::get('/api/ticket', [TicketController::class, 'get']);
Route::get('/api/login', [TicketController::class, 'login']);
Route::get('/api/advertisement/get_img', [AdvertisementController::class, 'getImg']);
Route::get('/api/advertisement/get_url', [AdvertisementController::class, 'getUrl']);
Route::get('/api/verify/get/{code}', [VerifyController::class, 'get']);
Route::get('/api/verify/clear/{code}', [VerifyController::class, 'clear']);
Route::get('/habbo-imaging/avatarimage', [ImagingController::class, 'avatarImage']);
Route::get('/habbo-imaging/badge/{path}', [ImagingController::class, 'badge'])->where('path', '.*');
Route::get('/habbo-imaging/badge-fill/{path}', [ImagingController::class, 'badgeFill'])->where('path', '.*');
Route::get('/trax/song/{song}', [TraxController::class, 'getSong']);
