<?php

return [
    'base_path' => env('HAVANA_BASE_PATH', '/opt/git/Havana'),
    'template_path' => env('HAVANA_TEMPLATE_PATH', env('HAVANA_BASE_PATH', '/opt/git/Havana').'/tools/www-tpl'),
    'template_name' => env('HAVANA_TEMPLATE_NAME', 'default'),
    'locale_file' => env('HAVANA_LOCALE_FILE', 'locale-en.ini'),
    'public_path' => env('HAVANA_PUBLIC_PATH', env('HAVANA_BASE_PATH', '/opt/git/Havana').'/tools/www'),
    'housekeeping_path' => env('HAVANA_HOUSEKEEPING_PATH', 'allseeingeye/hk'),
    'rcon' => [
        'host' => env('HAVANA_RCON_HOST', '127.0.0.1'),
        'port' => (int) env('HAVANA_RCON_PORT', 12309),
    ],
    'settings_defaults' => [
        'site.name' => 'Habbo',
        'site.path' => 'http://localhost',
        'static.content.path' => 'http://localhost',
        'site.imaging.endpoint' => 'http://localhost:5000',
        'site.imaging.endpoint.timeout' => '5000',
        'hotel.check.online' => 'true',
        'loader.game.ip' => '127.0.0.1',
        'loader.game.port' => '12321',
        'loader.mus.ip' => '127.0.0.1',
        'loader.mus.port' => '12322',
        'loader.dcr' => 'http://localhost/dcr/v31/habbo.dcr?',
        'loader.dcr.http' => 'http://localhost/dcr/v31/habbo.dcr?',
        'loader.external.variables' => 'http://localhost/dcr/v31/gamedata/external_variables.txt?',
        'loader.external.texts' => 'http://localhost/dcr/v31/gamedata/external_texts.txt?',
        'loader.flash.port' => '12323',
        'loader.flash.base' => 'http://localhost/gordon/RELEASE39-22643-22891-200911110035_07c3a2a30713fd5bea8a8caf07e33438/',
        'loader.flash.swf' => 'http://localhost/gordon/RELEASE39-22643-22891-200911110035_07c3a2a30713fd5bea8a8caf07e33438/Habbo.swf',
        'loader.flash.external.texts' => 'http://localhost/flash/gamedata/external_flash_texts.txt',
        'loader.flash.external.variables' => 'http://localhost/flash/gamedata/external_variables.txt',
        'registration.disabled' => 'false',
        'max.connections.per.ip' => '2',
        'homepage.template.file' => 'index_v32',
        'maintenance' => 'false',
        'group.purchase.cost' => '20',
        'group.default.badge' => 'b0503Xs09114s05013s05015',
        'hot.groups.community.limit' => '8',
        'hot.groups.limit' => '10',
        'discussions.per.page' => '10',
        'discussions.replies.per.page' => '10',
        'free.month.hc.registration' => 'true',
        'max.tags.users' => '8',
        'max.tags.groups' => '20',
        'trade.email.verification' => 'false',
        'email.smtp.enable' => 'false',
        'email.static.content.path' => 'http://localhost',
        'email.smtp.host' => '',
        'email.smtp.port' => '465',
        'email.smtp.login.username' => '',
        'email.smtp.login.password' => '',
        'email.smtp.from.email' => '',
        'email.smtp.from.name' => '',
        'reset.sso.after.login' => 'false',
    ],
];
